environment:

  matrix:

    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install MutPy"

build: off

test_script:
  - "%PYTHON%\\Scripts\\mut.py --target models --unit-test tests -c"
